spring.application.name=healthcare-backend
server.port=8081

# Database Configuration - Default to H2 Memory Db (MySQL mode)
spring.datasource.url=jdbc:h2:mem:healthcaredb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console setup
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Swagger OpenAPI docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT secrets
jwt.secret=7d4c783457df789234857bdf89cdefa897bcd789effebcd897fba9876cde3212
jwt.expiration=86400000

# File Upload Settings
file.upload.dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
